services:
  setoku:
    image: setoku
    build: .
    container_name: setoku
    ports:
      - "${SETOKU_PORT:-8000}:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped

volumes:
  setoku-data:
